name: 'Deploy to GitHub Pages'
description: 'This action will handle the building and deploying process of your project to GitHub Pages.'
author: 'Lim Kha Shing <kslim5703@gmail.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'