name: Github Pages

on:
  push:
    branches:
      - development
        
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install and Test
        run: |
          yarn
          yarn test
        env:
          CI: true

  build-and-deploy:
    runs-on: ubuntu-latest
    # using @master isn't sufficient as it will end up using an incompatible version number
    
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
      
      # The build script the action should run prior to deploying.
    - name: Build Production React.js page 🔧
      run: |
        npm install 
        npm run-script build 
      env:
        CI: false
       
    - name: Deploy to Github Pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: master # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
        clean: true
